-- File: tomorrow_night_dimmed.lua
-- https://github.com/deparr  

if vim.g.colors_name then vim.cmd "hi clear" end

vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "tairiki-dimmed"

local h = vim.api.nvim_set_hl
h(0,"@attribute",{link = "PreProc"})
h(0,"@boolean",{link = "Boolean"})
h(0,"@character",{link = "String"})
h(0,"@character.special",{link = "SpecialChar"})
h(0,"@comment",{link = "Comment"})
h(0,"@comment.error",{fg = "#c37d7c"})
h(0,"@comment.markdown",{fg = "#696969"})
h(0,"@comment.note",{fg = "#9bb0ac"})
h(0,"@comment.todo",{fg = "#d9bf89"})
h(0,"@comment.warning",{fg = "#d99667"})
h(0,"@constant",{link = "Constant"})
h(0,"@constant.builtin",{link = "@constant"})
h(0,"@constant.macro",{link = "Macro"})
h(0,"@constructor",{fg = "#c37d7c"})
h(0,"@diff.delta",{link = "DiffChange"})
h(0,"@diff.minus",{link = "DiffDelete"})
h(0,"@diff.plus",{link = "DiffAdd"})
h(0,"@function",{link = "Function"})
h(0,"@function.builtin",{fg = "#c37d7c"})
h(0,"@function.macro",{link = "Macro"})
h(0,"@keyword",{fg = "#b19db8"})
h(0,"@keyword.conditional",{link = "Conditional"})
h(0,"@keyword.coroutine",{fg = "#c37d7c"})
h(0,"@keyword.directive",{fg = "#c37d7c"})
h(0,"@keyword.function",{fg = "#b19db8"})
h(0,"@keyword.modifier",{fg = "#c37d7c"})
h(0,"@label",{fg = "#93a8b8"})
h(0,"@lsp.mod.abstract",{})
h(0,"@lsp.mod.async",{})
h(0,"@lsp.mod.declaration",{})
h(0,"@lsp.mod.defaultLibrary",{})
h(0,"@lsp.mod.definition",{})
h(0,"@lsp.mod.deprecated",{strikethrough = true})
h(0,"@lsp.mod.documentation",{})
h(0,"@lsp.mod.modification",{})
h(0,"@lsp.mod.readonly",{})
h(0,"@lsp.mod.static",{})
h(0,"@lsp.type",{})
h(0,"@lsp.type.builtinType",{link = "@type.builtin"})
h(0,"@lsp.type.class",{fg = "#d9bf89"})
h(0,"@lsp.type.comment",{fg = "#696969"})
h(0,"@lsp.type.decorator",{link = "Macro"})
h(0,"@lsp.type.enum",{fg = "#d9bf89"})
h(0,"@lsp.type.enumMember",{fg = "#d99667"})
h(0,"@lsp.type.event",{fg = "#c37d7c"})
h(0,"@lsp.type.function",{fg = "#93a8b8"})
h(0,"@lsp.type.interface",{fg = "#d9bf89"})
h(0,"@lsp.type.keyword",{fg = "#b19db8"})
h(0,"@lsp.type.macro",{link = "Macro"})
h(0,"@lsp.type.method",{fg = "#93a8b8"})
h(0,"@lsp.type.modifier",{fg = "#c37d7c"})
h(0,"@lsp.type.namespace",{fg = "#afb2b0"})
h(0,"@lsp.type.number",{fg = "#d99667"})
h(0,"@lsp.type.operator",{fg = "#c5c8c6"})
h(0,"@lsp.type.parameter",{fg = "#afb2b0"})
h(0,"@lsp.type.property",{fg = "#afb2b0"})
h(0,"@lsp.type.regexp",{fg = "#c37d7c"})
h(0,"@lsp.type.string",{fg = "#b3ba7e"})
h(0,"@lsp.type.struct",{fg = "#d9bf89"})
h(0,"@lsp.type.type",{fg = "#d9bf89"})
h(0,"@lsp.type.typeParameter",{fg = "#c3ac7b"})
h(0,"@lsp.type.variable",{fg = "#afb2b0"})
h(0,"@markup.heading",{link = "Title"})
h(0,"@markup.italic",{italic = true})
h(0,"@markup.link",{fg = "#93a8b8"})
h(0,"@markup.link.label",{fg = "#d99667"})
h(0,"@markup.link.url",{underline = true})
h(0,"@markup.list",{link = "Special"})
h(0,"@markup.list.checked",{bold = true,fg = "#ecc575"})
h(0,"@markup.list.unchecked",{bold = true,fg = "#959896"})
h(0,"@markup.math",{fg = "#9bb0ac"})
h(0,"@markup.quote",{fg = "#afb2b0"})
h(0,"@markup.raw",{link = "String"})
h(0,"@markup.strikethrough",{strikethrough = true})
h(0,"@markup.strong",{bold = true})
h(0,"@markup.underline",{underline = true})
h(0,"@module",{fg = "#a7afb2"})
h(0,"@module.builtin",{fg = "#c37d7c"})
h(0,"@number",{link = "Number"})
h(0,"@number.float",{link = "Float"})
h(0,"@operator",{link = "Operator"})
h(0,"@property",{fg = "#afb2b0"})
h(0,"@punctuation.bracket",{fg = "#858886"})
h(0,"@punctuation.delimiter",{fg = "#858886"})
h(0,"@punctuation.special",{fg = "#c37d7c"})
h(0,"@string",{link = "String"})
h(0,"@string.special.url",{fg = "#9bb0ac",underline = true})
h(0,"@string.special.url.comment",{link = "Comment"})
h(0,"@tag",{link = "Label"})
h(0,"@tag.attribute",{link = "@property"})
h(0,"@tag.builtin",{fg = "#c37d7c"})
h(0,"@tag.delimiter",{link = "Delimiter"})
h(0,"@type",{fg = "#d9bf89"})
h(0,"@type.builtin",{fg = "#d99667"})
h(0,"@variable",{fg = "#afb2b0"})
h(0,"@variable.builtin",{fg = "#c37d7c"})
h(0,"@variable.member",{fg = "#afb2b0"})
h(0,"@variable.parameter",{fg = "#afb2b0"})
h(0,"@variable.parameter.builtin",{fg = "#c37d7c"})
h(0,"Added",{fg = "#b3ba7e"})
h(0,"Bold",{bold = true})
h(0,"Boolean",{fg = "#d99667"})
h(0,"Changed",{fg = "#93a8b8"})
h(0,"Character",{fg = "#b3ba7e"})
h(0,"ColorColumn",{bg = "#242627"})
h(0,"Comment",{fg = "#696969",italic = true})
h(0,"Conceal",{fg = "#696969"})
h(0,"Conditional",{fg = "#b19db8"})
h(0,"Constant",{fg = "#d99667"})
h(0,"CurSearch",{bg = "#d99667",fg = "#1d1f21"})
h(0,"Cursor",{bg = "#afb2b0",fg = "#1d1f21"})
h(0,"CursorColumn",{bg = "#242627"})
h(0,"CursorIM",{bg = "#afb2b0",fg = "#1d1f21"})
h(0,"CursorLine",{bg = "#242627"})
h(0,"CursorLineFold",{link = "FoldColumn"})
h(0,"CursorLineNr",{bold = true,fg = "#afb2b0"})
h(0,"CursorLineSign",{link = "SignColumn"})
h(0,"Debug",{fg = "#d99667"})
h(0,"Define",{fg = "#b19db8"})
h(0,"Delimiter",{fg = "#858886"})
h(0,"DiagnosticError",{fg = "#c37d7c"})
h(0,"DiagnosticHint",{fg = "#858886"})
h(0,"DiagnosticInfo",{fg = "#9bb0ac"})
h(0,"DiagnosticOk",{fg = "#b3ba7e"})
h(0,"DiagnosticUnderlineError",{sp = "#c37d7c",undercurl = true,underline = false})
h(0,"DiagnosticUnderlineHint",{sp = "#858886",undercurl = true,underline = false})
h(0,"DiagnosticUnderlineInfo",{sp = "#9bb0ac",undercurl = true,underline = false})
h(0,"DiagnosticUnderlineOk",{sp = "#b3ba7e",undercurl = true,underline = false})
h(0,"DiagnosticUnderlineWarn",{sp = "#d99667",undercurl = true,underline = true})
h(0,"DiagnosticVirtualTextError",{bg = "#2e282a",fg = "#c37d7c"})
h(0,"DiagnosticVirtualTextHint",{bg = "#272a2b",fg = "#858886"})
h(0,"DiagnosticVirtualTextInfo",{bg = "#2a2e2f",fg = "#9bb0ac"})
h(0,"DiagnosticVirtualTextOk",{bg = "#2c2f2a",fg = "#b3ba7e"})
h(0,"DiagnosticVirtualTextWarn",{bg = "#302b28",fg = "#d99667"})
h(0,"DiagnosticWarn",{fg = "#d99667"})
h(0,"DiffAdd",{bg = "#4a4e3d",fg = "#afb2b0"})
h(0,"DiffChange",{bg = "#3c3f3f",fg = "#afb2b0"})
h(0,"DiffDelete",{bg = "#2e282a",fg = "#c37d7c"})
h(0,"DiffText",{bg = "#464f56",fg = "#afb2b0"})
h(0,"Directory",{fg = "#93a8b8"})
h(0,"EndOfBuffer",{fg = "#1d1f21"})
h(0,"Error",{fg = "#c37d7c"})
h(0,"ErrorMsg",{bold = true,fg = "#c37d7c"})
h(0,"Exception",{fg = "#c37d7c"})
h(0,"Float",{fg = "#d99667"})
h(0,"FloatBorder",{bg = "#242627",fg = "#959896"})
h(0,"FloatFooter",{link = "FloatTitle"})
h(0,"FloatTitle",{bg = "#242627",bold = true,fg = "#afb2b0"})
h(0,"FoldColumn",{link = "SignColumn"})
h(0,"Folded",{bg = "#242627",fg = "#afb2b0"})
h(0,"Function",{fg = "#93a8b8"})
h(0,"Identifier",{fg = "#afb2b0"})
h(0,"Ignore",{fg = "#959896"})
h(0,"IncSearch",{bg = "#d99667",fg = "#1d1f21"})
h(0,"Include",{fg = "#b19db8"})
h(0,"Italic",{italic = true})
h(0,"Keyword",{fg = "#b19db8"})
h(0,"Label",{fg = "#93a8b8"})
h(0,"LineNr",{fg = "#858886"})
h(0,"LineNrAbove",{link = "LineNr"})
h(0,"LineNrBelow",{link = "LineNr"})
h(0,"LspCodeLens",{fg = "#858886",italic = true})
h(0,"LspCodeLensSeparator",{fg = "#959896",italic = true})
h(0,"LspInfoBorder",{bg = "#242627",fg = "#959896"})
h(0,"LspInlayHint",{link = "NonText"})
h(0,"LspReferenceRead",{bg = "#323435"})
h(0,"LspReferenceTarget",{bg = "#323435"})
h(0,"LspReferenceText",{bg = "#323435"})
h(0,"LspReferenceWrite",{bg = "#323435"})
h(0,"LspSignatureActiveParameter",{bold = true,underline = true})
h(0,"Macro",{fg = "#d99667"})
h(0,"MatchParen",{fg = "#d99667"})
h(0,"ModeMsg",{fg = "#959896"})
h(0,"MoreMsg",{fg = "#b19db8"})
h(0,"MsgArea",{bg = "none",fg = "none"})
h(0,"MsgSeparator",{link = "StatusLine"})
h(0,"NonText",{fg = "#959896"})
h(0,"Normal",{bg = "#0c0d0e",fg = "#afb2b0"}) -- #1d1f21
h(0,"NormalFloat",{bg = "#242627",fg = "#afb2b0"})
h(0,"NormalNC",{bg = "none",fg = "none"})
h(0,"Number",{fg = "#d99667"})
h(0,"Operator",{fg = "#c5c8c6"})
h(0,"Pmenu",{bg = "#242627",fg = "#959896"})
h(0,"PmenuExtra",{link = "Pmenu"})
h(0,"PmenuExtraSel",{link = "PmenuSel"})
h(0,"PmenuKind",{link = "Pmenu"})
h(0,"PmenuKindSel",{link = "PmenuSel"})
h(0,"PmenuMatch",{bold = true})
h(0,"PmenuMatchSel",{bold = true})
h(0,"PmenuSbar",{bg = "#323435",fg = "none"})
h(0,"PmenuSel",{bg = "#323435",fg = "#93a8b8"})
h(0,"PmenuThumb",{bg = "#858886",fg = "#858886"})
h(0,"PreCondit",{fg = "#c37d7c"})
h(0,"PreProc",{fg = "#b19db8"})
h(0,"Question",{fg = "#d9bf89"})
h(0,"QuickFixLine",{bg = "#323435"})
h(0,"Removed",{fg = "#c37d7c"})
h(0,"Repeat",{fg = "#b19db8"})
h(0,"Search",{bg = "#d9bf89",fg = "#1d1f21"})
h(0,"SignColumn",{bg = "#1d1f21",fg = "#afb2b0"})
h(0,"SnippetTabstop",{link = "Visual"})
h(0,"Special",{bold = true,fg = "#c37d7c"})
h(0,"SpecialChar",{fg = "#c37d7c"})
h(0,"SpecialComment",{link = "Comment"})
h(0,"SpecialKey",{fg = "#959896"})
h(0,"SpellBad",{sp = "#c37d7c",undercurl = true,underline = false})
h(0,"SpellCap",{sp = "#959896",undercurl = true,underline = false})
h(0,"SpellLocal",{sp = "#959896",undercurl = true,underline = false})
h(0,"SpellRare",{sp = "#b19db8",undercurl = true,underline = false})
h(0,"Statement",{fg = "#c37d7c"})
h(0,"StatusLine",{bg = "#242627",fg = "#959896"})
h(0,"StatusLineNC",{bg = "#242627",fg = "#858886"})
h(0,"StatusLineTerm",{bg = "#242627",fg = "#959896"})
h(0,"StatusLineTermNC",{bg = "#242627",fg = "#858886"})
h(0,"StorageClass",{fg = "#c37d7c"})
h(0,"String",{fg = "#b3ba7e"})
h(0,"Structure",{fg = "#d9bf89"})
h(0,"Substitute",{link = "CurSearch"})
h(0,"TabLine",{bg = "#1d1f21",fg = "#696969"})
h(0,"TabLineFill",{bg = "#1d1f21"})
h(0,"TabLineSel",{bg = "#696969",fg = "#1d1f21"})
h(0,"Tag",{fg = "#c37d7c"})
h(0,"TermCursor",{link = "Cursor"})
h(0,"TermCursorNC",{})
h(0,"Title",{bold = true,fg = "#afb2b0"})
h(0,"Todo",{bold = true,fg = "#d99667"})
h(0,"Type",{fg = "#d9bf89"})
h(0,"Typedef",{fg = "#d9bf89"})
h(0,"Underlined",{underline = true})
h(0,"Visual",{bg = "#323435",bold = false,fg = "none"})
h(0,"VisualNOS",{link = "Visual"})
h(0,"WarningMsg",{bold = true,fg = "#d99667"})
h(0,"Whitespace",{fg = "#858886"})
h(0,"WildMenu",{link = "CurSearch"})
h(0,"WinBar",{link = "StatusLine"})
h(0,"WinBarNC",{link = "StatusLineNC"})
h(0,"WinSeparator",{fg = "#858886"})
h(0,"diffAdded",{link = "Added"})
h(0,"diffChanged",{link = "Changed"})
h(0,"diffFile",{fg = "#93a8b8"})
h(0,"diffLine",{fg = "#9bb0ac"})
h(0,"diffRemoved",{link = "Removed"})
h(0,"lCursor",{bg = "#afb2b0",fg = "#1d1f21"})

